version: '3.9'

services:
  nginx:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    ports:
      - "80:8080"
      - "443:4343"
      - "8000:8000"

  back:
    build:
      context: ./back
      dockerfile: ./Dockerfile
    restart: always
    env_file:
      - ./back/.env
    command: ["api:run"]

  front:
    build:
      context: ./front
      dockerfile: ./Dockerfile
    restart: always
