version: '3.9'

services:
  nginx:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    ports:
      - "80:8080"
      - "443:4343"
      - "8000:8000"

  back:
    build:
      context: ./back
      dockerfile: ./Dockerfile
    restart: always
    env_file:
      - dev.env
    command: ["api:run"]

  db:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_PASSWORD: ${RDBS_PASSWORD}
      POSTGRES_DB: monitoring
    volumes:
      - monitoring-db:/var/lib/postgresql/data

  migration:
    build:
      context: ./back
      dockerfile: ./Dockerfile
    restart: on-failure
    depends_on:
      - db
    env_file:
      - dev.env
    command: ["rdbs:upgrade"]

  front:
    build:
      context: ./front
      dockerfile: ./Dockerfile
    restart: always

volumes:
  monitoring-db:
