"""manager code

Revision ID: 559b173d8148
Revises: cfe05b74f2fe
Create Date: 2023-10-26 22:10:47.702167

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '559b173d8148'
down_revision = 'cfe05b74f2fe'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('code', sa.String(length=20), nullable=True))
    op.create_unique_constraint(op.f('uq__users__code'), 'users', ['code'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('uq__users__code'), 'users', type_='unique')
    op.drop_column('users', 'code')
    # ### end Alembic commands ###
