"""drop value field

Revision ID: cfe05b74f2fe
Revises: 6306cb603de7
Create Date: 2023-10-26 21:21:47.936169

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cfe05b74f2fe'
down_revision = '6306cb603de7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('feedbacks', 'value')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('feedbacks', sa.Column('value', sa.VARCHAR(length=200), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
