"""notify_at for devices

Revision ID: 2d6938f58ed0
Revises: 6306cb603de7
Create Date: 2024-01-15 17:55:24.940121

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2d6938f58ed0'
down_revision = '6306cb603de7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('devices', sa.Column('notify_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('devices', 'notify_at')
    # ### end Alembic commands ###
