version: '3.7'

services:
  vue:
    container_name: vue-urfu-web
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - VUE_APP_BASE_URL=http://159.223.224.135:8000/api/v1
    ports:
    - '8080:8080'